Use fast range instead of modulo for filter compression
Roasbeef/btcutil pull request #5
Opened 2017-09-25 22:03 UTC by aakselrod

Per the suggestion at https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-June/014530.html, this PR improves the performance of filter compression.

2017-10-25 22:11 UTC, Roasbeef requested changes

2017-10-25 22:11 UTC, Roasbeef commented on gcs/gcs.go
> +		v = ((((v >> 32) * N) >> 32) << (32 - f.p)) |
I think we should unpack this a bit, possible into distinct assignments with a brief comment explaining the rationale behind the shifts and OR's. As it exists now, I've grokked the computation, but it took a bit as everything is chained together. 

I'm assuming the compiler will eventually optimize it into a form like this, however for the sake of the reader I think we can make the operation a bit more clear.

2017-10-31 18:39 UTC, aakselrod commented on gcs/gcs.go
> +		v = ((((v >> 32) * N) >> 32) << (32 - f.p)) |
I've both corrected the computation and expanded/commented it. Since it doesn't give us a huge speedup due to the fact that other overhead takes significantly more time, I have left any additional optimization for later.

2017-11-02 23:54 UTC, Roasbeef commented on gcs/builder/builder.go
> +	b.AddEntries(witness)
As we're recursing into _each_ item within the witness stack, I don't think we need to index the main witness array.

2017-11-03 00:02 UTC, Roasbeef commented on gcs/builder/builder.go
> +	b.AddEntries(witness)
Talked offline and decided that it's correct as is.

2017-11-03 00:22 UTC, Roasbeef approved these changes
LGTM 🛰

2017-11-03 00:23 UTC, merged